### PR TITLE
Support for Broccoli v1

### PR DESCRIPTION
**Pull request by stfsy**
- Rewrote the plugin to support the new broccoli plugin api 
- Extended caching writer to gain performance improvements
- Added mocha tests
- Cleaned up repository and dependencies

### CODE REVIEW

**Comment by Alinaki** [comment]
Maybe you should start a new npm plugin for your fork? Seems like author won't merge that :(

**Comment by Harris-Miller** [comment]
Either of you two want to take over this project on npm? I'm no longer an active Ember contributor

**Comment by stfsy** [comment]
Yep you can transfer the ownership to me

**Comment by stfsy** [comment]
https://www.npmjs.com/~stfsy

**Comment by Harris-Miller** [comment]
@stfsy I made you an owner of the npm package, and added you as a contributor to this repo. Let me know once you've verified those and I'll transfer this Repo over to you as well

**Comment by stfsy** [comment]
checked both, looking good

**Comment by Harris-Miller** [comment]
@stfsy you have to delete your fork, then I can transfer ownership to you, also I accepted the pull-request

**Comment by stfsy** [comment]
@Harris-Miller yeah renaming was appearently not enough. deleted my fork

**Comment by Harris-Miller** [comment]
@stfsy enjoy!

**Pull request merged**
